Global RefHeight := 1080
Global RefWidth := 1920
Global CurrentHeight := A_ScreenHeight
Global CurrentWidth := A_ScreenWidth
Global ClickFX := 960
Global ClickFY := 333
Global NewFX := (ClickFX / RefWidth) * CurrentWidth
Global NewFY := (ClickFY / RefHeight) * CurrentHeight
Global ClickBX :=960
Global ClickBY :=810
Global NewBX := (ClickBX / RefWidth) * CurrentWidth
Global NewBY := (ClickBY / RefHeight) * CurrentHeight
Global ClickRX :=1260
Global ClickRY :=540
Global NewRX := (ClickRX / RefWidth) * CurrentWidth
Global NewRY := (ClickRY / RefHeight) * CurrentHeight
Global ClickDX :=960
Global ClickDY :=540
Global NewDX := (ClickDX / RefWidth) * CurrentWidth
Global NewDY := (ClickDY / RefHeight) * CurrentHeight
Global RClickU :=450
Global RClickD :=950
Global RClickX :=600
Global RNewU := (RClickU / RefHeight) * CurrentWidth
Global RNewD := (RClickD / RefHeight) * CurrentHeight
Global RNewX := (RClickX / RefWidth) * CurrentHeight
Global TLX := 24
Global TLY := 505
Global BRX := 230
Global BRY := 70
Global NewTLX := (TLX / RefWidth) * CurrentWidth
Global NewTLY := (TLY / RefHeight) * CurrentHeight
Global NewBRX := (BRX / RefWidth) * CurrentWidth
Global NewBRY := (BRY / RefHeight) * CurrentHeight
