RefHeight := 1080
RefWidth := 1920
CurrentHeight := A_ScreenHeight
CurrentWidth := A_ScreenWidth
ClickFX := 960
ClickFY := 333
NewFX := (ClickFX / RefWidth) * CurrentWidth
NewFY := (ClickFY / RefHeight) * CurrentHeight
ClickBX :=960
ClickBY :=810
NewBX := (ClickBX / RefWidth) * CurrentWidth
NewBY := (ClickBY / RefHeight) * CurrentHeight
ClickRX :=1260
ClickRY :=540
NewRX := (ClickRX / RefWidth) * CurrentWidth
NewRY := (ClickRY / RefHeight) * CurrentHeight
ClickDX :=960
ClickDY :=540
NewDX := (ClickDX / RefWidth) * CurrentWidth
NewDY := (ClickDY / RefHeight) * CurrentHeight
RClickU :=450
RClickD :=950
RClickX :=600
RNewU := (RClickU / RefHeight) * CurrentWidth
RNewD := (RClickD / RefHeight) * CurrentHeight
RNewX := (RClickX / RefWidth) * CurrentHeight